name: Run Tests

on:
  push:
    branches:
      - feat/dev
      - main
      - v0-final
    paths-ignore:
      - ".github/workflows/release.yml"
      - "README.md"
  pull_request:
    branches:
      - feat/dev
      - main
      - v0-final

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Unit test
        # Skip TestCloudflareDetection here, as most IP addresses of Github's action
        # runners have been marked as bot.
        run: go test -skip TestCloudflareDetection -v ./...
