name: Run Tests

on:
  push:
    branches:
      - main
      - "release/**"
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"
  pull_request:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Unit test
        # Skip TestCloudflareDetection here, as most IP addresses of Github's action
        # runners have been marked as bot.
        run: go test -skip TestCloudflareDetection -v ./...
